# Generated by Django 2.2.5 on 2019-09-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
