# Generated by Django 2.2.5 on 2019-10-23 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageDomain', '0001_initial'),
        ('account', '0004_auto_20191017_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainUser',
            fields=[
                ('domainuserid', models.AutoField(primary_key=True, serialize=False)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDomain.DomainModel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
