# Generated by Django 2.2.5 on 2019-10-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_domainuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
