# Generated by Django 2.2.5 on 2019-10-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainUser',
        ),
    ]
