# Generated by Django 2.2.5 on 2019-10-09 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainModel',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='relationModel',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_label', models.CharField(max_length=50)),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDomain.DomainModel')),
            ],
        ),
        migrations.CreateModel(
            name='entityModel',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_label', models.CharField(max_length=50)),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDomain.DomainModel')),
            ],
        ),
    ]
