# Generated by Django 2.2.5 on 2019-10-23 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageDomain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainmodel',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
