# Generated by Django 2.2.7 on 2019-11-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageDomain', '0002_domainmodel_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainmodel',
            options={'verbose_name': '领域管理', 'verbose_name_plural': '领域管理'},
        ),
        migrations.AlterModelOptions(
            name='entitymodel',
            options={'verbose_name': '实体管理', 'verbose_name_plural': '实体管理'},
        ),
        migrations.AlterModelOptions(
            name='relationmodel',
            options={'verbose_name': '关系管理', 'verbose_name_plural': '关系管理'},
        ),
        migrations.AlterField(
            model_name='domainmodel',
            name='domain_name',
            field=models.CharField(max_length=50, verbose_name='领域名称'),
        ),
        migrations.AlterField(
            model_name='entitymodel',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDomain.DomainModel', verbose_name='所属领域'),
        ),
        migrations.AlterField(
            model_name='entitymodel',
            name='entity_label',
            field=models.CharField(max_length=50, verbose_name='实体属性名称'),
        ),
        migrations.AlterField(
            model_name='relationmodel',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDomain.DomainModel', verbose_name='所属领域'),
        ),
        migrations.AlterField(
            model_name='relationmodel',
            name='relation_label',
            field=models.CharField(max_length=50, verbose_name='关系属性名称'),
        ),
    ]
